version: "3.2"

services:
  robodoc:
    build:
      context: .
    environment: 
      - DOCKER_UID=${DOCKER_UID}
      - DOCKER_GID=${DOCKER_GID}
    image: andyneff/robodoc:latest
    volumes:
      - ${SRC_DIR}:/src
      - ${DOC_DIR}:/doc